title: Keyur Vanmalibhai Borad
description:  a passionate robotics enthusiast dedicated to pushing the boundaries of technology and innovation. With a strong foundation in mechanical engineering, computer science, and artificial intelligence, I thrive on creating intelligent systems that can revolutionize industries and enhance everyday life.
logo: /assets/img/keyur.jpg
theme: jekyll-theme-minimal
